 ## Numpy

In [1]:
import numpy as np                #Importing the Numpy package



In [2]:
a= np.array([1,4,5,8], float)                # Creating Numpy array with Float variables



In [3]:
print(type(a))                #Type of variable



<class 'numpy.ndarray'>


In [4]:
# Operations on the array
a[0] = 5                #Replacing the first element of the array
print(a)



[5. 4. 5. 8.]


In [5]:
b = np.array([[1,2,3],[4,5,6]], float)                #Creating a 2-D numpy array
b[0,1]                                        # Fetching second element of 1st array



2.0

In [6]:
print(b.shape)                #Returns tuple with the shape of array



(2, 3)


In [7]:
b.dtype                #Returns the type of the value stored



dtype('float64')

In [8]:
print(len(b))                #Returns length of the first axis



2


In [9]:
2 in b                #'in' searches for the element in the array



True

In [10]:
0 in b



False

In [11]:
# Use of 'reshape' : transforms elements from 1-D to 2-D here
c = np.array(range(12), float)
print(c)
print(c.shape)
print('---')
c = c.reshape((2,6))    # reshape the array in the new form
print(c)
print(c.shape)



[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
(12,)
---
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
(2, 6)


In [12]:
c.fill(0)                #Fills whole array with single value, done inplace
print(c)



[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [13]:
c.transpose()                #creates transpose of the array, not done inplace



array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
c.flatten()                #flattens the whole array, not done inplace



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
# Concatenation of 2 or more arrays
m = np.array([1,2], float)
n = np.array([3,4,5,6], float)
p = np.concatenate((m,n))
print(p)
print(p.shape)



[1. 2. 3. 4. 5. 6.]
(6,)


In [16]:
# 'newaxis' : to increase the dimensonality of the array
q = np.array([1,2,3], float)
q[:, np.newaxis].shape



(3, 1)

In [17]:
a1 = np.array([[1,2],[3,4],[5,6]], float)
a2 = np.array([-1,3], float)

print(a1+a2)



[[0. 5.]
 [2. 7.]
 [4. 9.]]


In [18]:
a3 = np.array([[0,2],[3,-1],[3,5]], float)
print(a3.mean(axis=0))                        #Mean of elements column-wise
print(a3.mean(axis=1))                        #Mean of elements row-wise



[2. 2.]
[1. 1. 4.]


In [19]:
a4 = np.array([1,3,0], float)
np.where(a!=0, 1/a ,a)



array([0.2  , 0.25 , 0.2  , 0.125])

In [20]:
np.random.rand(2,3)


array([[0.25387739, 0.53498898, 0.20756523],
       [0.25762637, 0.94388355, 0.19828086]])

In [21]:
print("new")


new
